# Generated by Django 2.2.5 on 2019-11-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reachweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(choices=[('Juja', 'Gachororo'), ('High Point', 'Sewage'), ('K-road', 'Stage'), ('Gwa-Kairu', 'Estate'), ('Ruiru', 'Kimbo')], default='Ruiru', max_length=200),
        ),
    ]
