# Generated by Django 2.2.5 on 2019-11-01 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='prof.jpg', upload_to='dash_profile_pics/')),
                ('contact', models.CharField(max_length=250)),
                ('hospital', models.CharField(max_length=250)),
                ('role', models.CharField(choices=[('Doc', 'Doctor'), ('Sur', 'Surgeon'), ('Nur', 'Nurse')], max_length=200)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ['name'],
            },
        ),
    ]
