# Generated by Django 2.2.5 on 2019-11-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='dash_profiles',
        ),
    ]
